cluster_name: "Kubernetes Cluster"
network:
  control_ip: "192.168.56.10"
  worker_ip: "192.168.56.20"
  postgres_ip: "192.168.56.30" # IP estática base para Postgres
  dns_servers:
    - 8.8.8.8
    - 1.1.1.1
  pod_cidr: "172.16.1.0/16"
  service_cidr: "172.17.1.0/18"
nodes:
  # Nodos de control
  control:
    count: 1
    cpu: 2
    memory: 4096
  postgre:
    count: 1 # Inicialmente 1 para tus pruebas locales
    cpu: 1
    memory: 2048
  workers:
    count: 2
    cpu: 1
    memory: 2048
software:
  box: "bento/ubuntu-24.04"
  calico: "3.31.0"
  dashboard: "7.14.0"
  kubernetes: "1.34.0-*"
  helm: "3.21.2"
  os: "xUbuntu_24.04"
shared_folders:
  - host_path: "../images"
    vm_path: "/vagrant/images"